---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 10
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-k4ben
  template:
    metadata:
      labels:
        app: birds-app-back-end-k4ben
    spec:
      containers:
        - image: 'ghcr.io/k4ben/birds-app-back-end:4f8b643f0ba0fbeba40b5fa530bcdded412927b1'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
